TEAM_ASSETS = {
    "Arizona Diamondbacks": {"abbr": "ARI", "logo": "https://www.mlbstatic.com/team-logos/109.svg"},
    "Athletics": {"abbr": "OAK", "logo": "https://www.mlbstatic.com/team-logos/133.svg"},
    "Atlanta Braves": {"abbr": "ATL", "logo": "https://www.mlbstatic.com/team-logos/144.svg"},
    "Baltimore Orioles": {"abbr": "BAL", "logo": "https://www.mlbstatic.com/team-logos/110.svg"},
    "Boston Red Sox": {"abbr": "BOS", "logo": "https://www.mlbstatic.com/team-logos/111.svg"},
    "Chicago Cubs": {"abbr": "CHC", "logo": "https://www.mlbstatic.com/team-logos/112.svg"},
    "Chicago White Sox": {"abbr": "CWS", "logo": "https://www.mlbstatic.com/team-logos/145.svg"},
    "Cincinnati Reds": {"abbr": "CIN", "logo": "https://www.mlbstatic.com/team-logos/113.svg"},
    "Cleveland Guardians": {"abbr": "CLE", "logo": "https://www.mlbstatic.com/team-logos/114.svg"},
    "Colorado Rockies": {"abbr": "COL", "logo": "https://www.mlbstatic.com/team-logos/115.svg"},
    "Detroit Tigers": {"abbr": "DET", "logo": "https://www.mlbstatic.com/team-logos/116.svg"},
    "Houston Astros": {"abbr": "HOU", "logo": "https://www.mlbstatic.com/team-logos/117.svg"},
    "Kansas City Royals": {"abbr": "KC", "logo": "https://www.mlbstatic.com/team-logos/118.svg"},
    "Los Angeles Angels": {"abbr": "LAA", "logo": "https://www.mlbstatic.com/team-logos/108.svg"},
    "Los Angeles Dodgers": {"abbr": "LAD", "logo": "https://www.mlbstatic.com/team-logos/119.svg"},
    "Miami Marlins": {"abbr": "MIA", "logo": "https://www.mlbstatic.com/team-logos/146.svg"},
    "Milwaukee Brewers": {"abbr": "MIL", "logo": "https://www.mlbstatic.com/team-logos/158.svg"},
    "Minnesota Twins": {"abbr": "MIN", "logo": "https://www.mlbstatic.com/team-logos/142.svg"},
    "New York Mets": {"abbr": "NYM", "logo": "https://www.mlbstatic.com/team-logos/121.svg"},
    "New York Yankees": {"abbr": "NYY", "logo": "https://www.mlbstatic.com/team-logos/147.svg"},
    "Philadelphia Phillies": {"abbr": "PHI", "logo": "https://www.mlbstatic.com/team-logos/143.svg"},
    "Pittsburgh Pirates": {"abbr": "PIT", "logo": "https://www.mlbstatic.com/team-logos/134.svg"},
    "San Diego Padres": {"abbr": "SD", "logo": "https://www.mlbstatic.com/team-logos/135.svg"},
    "San Francisco Giants": {"abbr": "SF", "logo": "https://www.mlbstatic.com/team-logos/137.svg"},
    "Seattle Mariners": {"abbr": "SEA", "logo": "https://www.mlbstatic.com/team-logos/136.svg"},
    "St. Louis Cardinals": {"abbr": "STL", "logo": "https://www.mlbstatic.com/team-logos/138.svg"},
    "Tampa Bay Rays": {"abbr": "TB", "logo": "https://www.mlbstatic.com/team-logos/139.svg"},
    "Texas Rangers": {"abbr": "TEX", "logo": "https://www.mlbstatic.com/team-logos/140.svg"},
    "Toronto Blue Jays": {"abbr": "TOR", "logo": "https://www.mlbstatic.com/team-logos/141.svg"},
    "Washington Nationals": {"abbr": "WAS", "logo": "https://www.mlbstatic.com/team-logos/120.svg"},
}